/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getMe"];
        put: operations["UsersController_updateMe"];
        post?: never;
        delete: operations["UsersController_removeMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExercisesController_findAll"];
        put?: never;
        post: operations["ExercisesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExercisesController_findOne"];
        put: operations["ExercisesController_update"];
        post?: never;
        delete: operations["ExercisesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutTemplatesController_findAll"];
        put?: never;
        post: operations["WorkoutTemplatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutTemplatesController_findOne"];
        put: operations["WorkoutTemplatesController_update"];
        post?: never;
        delete: operations["WorkoutTemplatesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutSessionsController_findAll"];
        put?: never;
        post: operations["WorkoutSessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutSessionsController_findOne"];
        put: operations["WorkoutSessionsController_update"];
        post?: never;
        delete: operations["WorkoutSessionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/sets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SessionSetsController_bulkUpdate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionSetsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SessionSetsController_update"];
        post?: never;
        delete: operations["SessionSetsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/exercise/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_getExerciseProgression"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/activity-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_getActivityDates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_getPersonalRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FavoritesController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{entity_type}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["FavoritesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{entity_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_findByType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
            /** @example John */
            display_name?: string;
            /**
             * @default male
             * @enum {string}
             */
            sex: "male" | "female";
            /**
             * @default kg
             * @enum {string}
             */
            unit_system: "kg" | "lbs";
        };
        TokenPairDto: {
            access_token: string;
            refresh_token: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        ChangePasswordDto: {
            /** @example oldPassword123 */
            current_password: string;
            /** @example newPassword123 */
            new_password: string;
        };
        UserResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example user@example.com */
            email: string;
            display_name?: string | null;
            /** @enum {string} */
            sex: "male" | "female";
            /** @enum {string} */
            unit_system: "kg" | "lbs";
            /** @enum {string} */
            role: "user" | "admin";
            preferences?: Record<string, never> | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateUserPreferencesDto: {
            /** @example fr */
            language?: string;
            /** @example dark */
            theme?: string;
        };
        UpdateUserDto: {
            display_name?: string;
            /** @enum {string} */
            unit_system?: "kg" | "lbs";
            preferences?: components["schemas"]["UpdateUserPreferencesDto"];
        };
        ExerciseResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example bench_press */
            slug: string;
            /** @enum {string} */
            muscle_group: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "glutes" | "core" | "cardio" | "full_body";
            /** @enum {string} */
            tracking_type: "strength" | "duration";
            is_global: boolean;
            notes?: string | null;
            /** Format: uuid */
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateExerciseDto: {
            /** @example bench_press */
            slug: string;
            /** @enum {string} */
            muscle_group: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "glutes" | "core" | "cardio" | "full_body";
            /** @default false */
            is_global: boolean;
            /**
             * @default strength
             * @enum {string}
             */
            tracking_type: "strength" | "duration";
            notes?: string;
        };
        UpdateExerciseDto: {
            /** @example bench_press */
            slug?: string;
            /** @enum {string} */
            muscle_group?: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "glutes" | "core" | "cardio" | "full_body";
            is_global?: boolean;
            /**
             * @default strength
             * @enum {string}
             */
            tracking_type: "strength" | "duration";
            notes?: string;
        };
        TemplateCreatorDto: {
            /** Format: uuid */
            id: string;
            display_name?: string | null;
            email: string;
        };
        TemplateExerciseResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            exercise_id: string;
            exercise: components["schemas"]["ExerciseResponseDto"];
            order_index: number;
            target_sets?: number | null;
            target_reps?: number | null;
            rest_seconds?: number | null;
            target_duration_min?: number | null;
        };
        TemplateResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            user?: components["schemas"]["TemplateCreatorDto"];
            /** @example Push Day */
            name: string;
            description?: string | null;
            /** @description Estimated duration in minutes */
            estimated_duration?: number | null;
            /** @default false */
            is_public: boolean;
            template_exercises: components["schemas"]["TemplateExerciseResponseDto"][];
            /** Format: date-time */
            created_at: string;
        };
        TemplateExerciseItemDto: {
            /** Format: uuid */
            exercise_id: string;
            order_index: number;
            target_sets?: number;
            target_reps?: number;
            rest_seconds?: number;
            target_duration_min?: number;
        };
        CreateTemplateDto: {
            /** @example Push Day */
            name: string;
            description?: string;
            /** @description Estimated duration in minutes */
            estimated_duration?: number;
            /** @default false */
            is_public: boolean;
            exercises?: components["schemas"]["TemplateExerciseItemDto"][];
        };
        UpdateTemplateDto: {
            /** @example Push Day */
            name?: string;
            description?: string;
            estimated_duration?: number;
            is_public?: boolean;
            exercises?: components["schemas"]["TemplateExerciseItemDto"][];
        };
        SetSegmentDto: {
            reps: number;
            weight_kg?: number | null;
        };
        SetResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            exercise_id: string;
            exercise: components["schemas"]["ExerciseResponseDto"];
            set_index: number;
            exercise_order: number;
            reps?: number | null;
            weight_kg?: number | null;
            duration_min?: number | null;
            segments?: components["schemas"]["SetSegmentDto"][] | null;
            is_pr: boolean;
            /** Format: date-time */
            performed_at?: string | null;
        };
        SessionResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            template_id?: string | null;
            /** @example 2026-05-08 */
            scheduled_date: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            notes?: string | null;
            session_sets: components["schemas"]["SetResponseDto"][];
            /**
             * Format: uuid
             * @description The ID of the last session with same template for this user
             */
            last_session_id?: string | null;
        };
        CreateSessionDto: {
            /** @example 2026-05-08 */
            scheduled_date: string;
            /** Format: uuid */
            template_id?: string;
        };
        UpdateSessionDto: {
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            ended_at?: string;
            notes?: string;
        };
        UpdateSetItemDto: {
            set_index?: number;
            exercise_order?: number;
            reps?: number;
            weight_kg?: number;
            duration_min?: number;
            /** Format: date-time */
            performed_at?: string;
            /** @description Segments successifs (drop set) ; null pour repasser à une série simple */
            segments?: components["schemas"]["SetSegmentDto"][] | null;
            /** Format: uuid */
            id: string;
        };
        CreateSetDto: {
            /** Format: uuid */
            exercise_id: string;
            set_index: number;
            /** @default 0 */
            exercise_order: number;
            reps?: number;
            weight_kg?: number;
            duration_min?: number;
            /** Format: date-time */
            performed_at?: string;
            /** @description Segments successifs (drop set) */
            segments?: components["schemas"]["SetSegmentDto"][];
        };
        BulkUpdateSetsDto: {
            updates: components["schemas"]["UpdateSetItemDto"][];
            creates?: components["schemas"]["CreateSetDto"][];
        };
        UpdateSetDto: {
            set_index?: number;
            exercise_order?: number;
            reps?: number;
            weight_kg?: number;
            duration_min?: number;
            /** Format: date-time */
            performed_at?: string;
            /** @description Segments successifs (drop set) ; null pour repasser à une série simple */
            segments?: components["schemas"]["SetSegmentDto"][] | null;
        };
        ExerciseProgressionPointDto: {
            /** @example 2026-05-08 */
            date: string;
            max_weight_kg: number;
        };
        PersonalRecordDto: {
            /** Format: uuid */
            exercise_id: string;
            exercise_slug: string;
            max_weight_kg: number;
            muscle_group: string;
            /** Format: date-time */
            performed_at?: string | null;
        };
        CreateFavoriteDto: {
            /**
             * @example template
             * @enum {string}
             */
            entity_type: "template";
            /** Format: uuid */
            entity_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_removeMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExercisesController_findAll: {
        parameters: {
            query?: {
                muscle_group?: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "glutes" | "core" | "cardio" | "full_body";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"][];
                };
            };
        };
    };
    ExercisesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"];
                };
            };
        };
    };
    ExercisesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"];
                };
            };
        };
    };
    ExercisesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExerciseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"];
                };
            };
        };
    };
    ExercisesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutTemplatesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"][];
                };
            };
        };
    };
    WorkoutTemplatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"];
                };
            };
        };
    };
    WorkoutTemplatesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"];
                };
            };
        };
    };
    WorkoutTemplatesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"];
                };
            };
        };
    };
    WorkoutTemplatesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutSessionsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by month (YYYY-MM) */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"][];
                };
            };
        };
    };
    WorkoutSessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    WorkoutSessionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    WorkoutSessionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    WorkoutSessionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionSetsController_bulkUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateSetsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetResponseDto"][];
                };
            };
        };
    };
    SessionSetsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetResponseDto"];
                };
            };
        };
    };
    SessionSetsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetResponseDto"];
                };
            };
        };
    };
    SessionSetsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatsController_getExerciseProgression: {
        parameters: {
            query?: {
                from?: string;
            };
            header?: never;
            path: {
                exerciseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseProgressionPointDto"][];
                };
            };
        };
    };
    StatsController_getActivityDates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 2026-05-14 */
                        date: string;
                        /** Format: uuid */
                        session_id: string;
                    }[];
                };
            };
        };
    };
    StatsController_getPersonalRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecordDto"][];
                };
            };
        };
    };
    FavoritesController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFavoriteDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_findByType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
